# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBFile',
            fields=[
                ('name', models.CharField(max_length=100,
                                          serialize=False)),
                ('filehash', models.CharField(max_length=32,
                    primary_key=True,
                    serialize=False)),
                ('content_type', models.CharField(max_length=100)),
                ('b64', models.TextField()),
            ],
        ),
    ]
