# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0002_add_filehash_rename_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
