# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0003_auto_remove_serialize'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbfile',
            name='mtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
