# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0004_dbfile_mtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='filehash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dbfile',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
