# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0005_auto_20170127_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbfile',
            name='filehash',
        ),
    ]
