# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0008_auto_20170206_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dbfile',
            name='primary_key',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
