# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0011_auto_20170206_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
